### PR TITLE
Don't paginate checkpoints for PDF

### PR DESCRIPTION
**Pull request by joecridge**
This actually works much better than I was expecting XD. I'll deploy it onto the server in a second, take a look.

Feel free to gridify :)

### CODE REVIEW

**Comment by danielswaine** [comment]
I've kind of got the grids working. It's just getting the data into the right box XD I thought it could be done with loops but not sure. What do you think?

**Comment by joecridge** [comment]
You've not pushed up your branch so I can't see :P

**Comment by danielswaine** [comment]
image

**Comment by danielswaine** [comment]
screen shot 2015-10-03 at 21 59 41

**Pull request merged**
